FROM nvcr.io/nvidia/pytorch:20.03-py3

RUN apt update && apt install -y sudo git
RUN apt install -y software-properties-common
RUN apt install -y libsm6 libxext6 libxrender-dev
RUN apt install -y libpng-dev libfreetype6-dev
RUN apt-get install -y libgl1-mesa-dev
RUN apt install -y tmux wget curl zip

RUN pip install -U pip 
RUN pip install -U pandas pillow
RUN pip install tqdm flake8
RUN pip install seaborn scikit-learn
RUN pip install shape-commentator future
RUN pip install jupyter 
RUN pip install -U  opencv-python

RUN mkdir /mnt/fs2
RUN mkdir -p /mnt/HDD8T/takamuro
COPY .tmux.conf /root/

WORKDIR /home/sota/data/m2/

# docker run -v /mnt/HDD8T/takamuro/:/mnt/HDD8T/takamuro -v /mnt/fs2:/mnt/fs2 -v /mnt/HDD8T/takamuro/m2/Weather_UNet_v2/:/home/sota/data/m2/ --gpus all --name weatherUNetV2 --shm-size 2G -p 6006:6006 -p 6007:6007 -it pytorch15_takamuro bash