FROM nvcr.io/nvidia/pytorch:20.11-py3

RUN apt update && apt install -y sudo git
RUN apt install -y software-properties-common
RUN apt install -y libsm6 libxext6 libxrender-dev
RUN apt install -y libpng-dev libfreetype6-dev
RUN apt install -y libgl1-mesa-dev
RUN apt install -y tmux wget curl zip
RUN apt install -y ffmpeg

RUN pip install -U pip 
RUN pip install -U tqdm flake8
RUN pip install -U scikit-learn
RUN pip install -U future
RUN pip install -U jupyter 
RUN pip install -U opencv-python
RUN pip uninstall -y pillow pandas
RUN conda install -y seaborn

RUN mkdir /mnt/fs2
RUN mkdir -p /mnt/HDD8T/takamuro
COPY .tmux.conf /root/

RUN git config --global user.name "temp"
RUN git config --global user.email temp@gmail.com

WORKDIR /home/sota/data/m2/

# docker run -v /mnt/SSD2T/takamuro/:/mnt/HDD8T/takamuro -v /mnt/fs2:/mnt/fs2 -v /mnt/HDD8T/takamuro/m2/Weather_UNet_v2/:/home/sota/data/m2/ --gpus all --name weatherUNetV2 --shm-size 16G -it torch18_takamuro bash